import LegalPage from "@/components/legal/LegalPage";

const AiUse = () => (
  <LegalPage
    title="How DRM uses AI"
    metaDescription="DRM's AI Use Notice: how AI-generated content is labeled, what is currently disabled, safety boundaries, and consent and deletion choices."
    path="/ai-use"
  >
    <p>
      DRM uses clear labels when content is generated by AI. AI output is educational and can be
      incomplete or wrong. It does not diagnose, prescribe, monitor emergencies, or replace a
      qualified healthcare professional.
    </p>

    <h2>Current release state</h2>
    <p>
      Health-sensitive AI processing is currently disabled. Public membership, price, login, and
      navigation questions use a deterministic local answer path. DRM must not send pre-consent free
      text to an outside AI or classifier.
    </p>

    <h2>If a health-AI feature is enabled later</h2>
    <p>
      The feature must first identify the purpose, the health-data categories involved, the
      providers, retention, and your choice. You must actively agree before health information is
      sent through Lovable AI Gateway to Google Gemini. Declining may not block non-health
      membership help. DRM sends the minimum necessary context and does not include payment-card
      data, unrelated logs, or identity fields the model does not need.
    </p>

    <h2>Labels and reporting</h2>
    <p>
      AI answer cards say <strong>AI-generated • Educational only</strong>. Meal plans say{" "}
      <strong>AI-generated meal plan</strong>. You can report an answer or meal plan without storing
      the raw health text in the report record. Verified DRM-team answers keep a separate label.
    </p>

    <h2>Safety</h2>
    <p>
      Do not use AI output to change medicine or respond to an emergency. Uncertain, medication,
      personal-result, fasting, and emergency messages use DRM's approved safety boundary rather
      than personalized medical instructions.
    </p>

    <h2>Consent and deletion</h2>
    <p>
      You can withdraw feature-specific health-data consent and request chat or account deletion.
      Withdrawal stops new processing; it does not undo processing that already occurred. Processor
      retention/deletion limits must be stated in the Privacy Notice before health AI is enabled.
    </p>
  </LegalPage>
);

export default AiUse;
