// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-program-status.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_program_status_default = defineTool({
  name: "get_program_status",
  title: "Get program status",
  description: "Return the signed-in member's current program day, streak counters, XP/level, and subscription status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb(ctx);
    const userId = ctx.getUserId();
    const [dayRes, streakRes, subRes, profileRes] = await Promise.all([
      client.rpc("current_program_day", { p_user_id: userId }),
      client.from("user_streaks").select("*").eq("user_id", userId).maybeSingle(),
      client.from("subscriptions").select("status, current_period_end, plan").eq("user_id", userId).in("status", ["trialing", "active", "past_due", "canceled"]).order("created_at", { ascending: false }).limit(1).maybeSingle(),
      client.from("profiles").select("first_name, timezone").eq("user_id", userId).maybeSingle()
    ]);
    const payload = {
      program_day: dayRes.data ?? null,
      streak: streakRes.data ?? null,
      subscription: subRes.data ?? null,
      profile: profileRes.data ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-today-action.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_today_action_default = defineTool2({
  name: "get_today_action",
  title: "Get today's action",
  description: "Return today's daily action (title, description, learning objective, sub-tasks) for the signed-in member, plus whether they've already completed it.",
  inputSchema: {
    day_number: z.number().int().min(1).max(120).optional().describe("Optional. Override the day to fetch; defaults to the member's current program day.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ day_number }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb2(ctx);
    const userId = ctx.getUserId();
    let day = day_number;
    if (!day) {
      const { data } = await client.rpc("current_program_day", { p_user_id: userId });
      day = data ?? 1;
    }
    const [{ data: action, error: aErr }, { data: progress }] = await Promise.all([
      client.from("daily_actions").select("day_number, day_name, phase_number, action_title, action_description, action_type, learning_objective, sub_tasks").eq("day_number", day).eq("is_extension_day", false).maybeSingle(),
      client.from("member_progress").select("completed_at, metadata").eq("user_id", userId).eq("day_number", day).maybeSingle()
    ]);
    if (aErr) return { content: [{ type: "text", text: aErr.message }], isError: true };
    const payload = { day, action, completed: !!progress, progress };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-blood-sugar.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blood_sugar_default = defineTool3({
  name: "list_blood_sugar_readings",
  title: "List blood sugar readings",
  description: "List the signed-in member's recent blood sugar readings (fasting, post-meal, random, or CGM), newest first.",
  inputSchema: {
    days: z2.number().int().min(1).max(90).optional().describe("Days back to include (default 7)."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb3(ctx);
    const since = new Date(Date.now() - (days ?? 7) * 864e5).toISOString();
    const { data, error } = await client.from("blood_sugar_readings").select("id, measured_at, value_mgdl, reading_type, source, notes").eq("member_id", ctx.getUserId()).gte("measured_at", since).order("measured_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { readings: data }
    };
  }
});

// src/lib/mcp/tools/log-blood-sugar.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_blood_sugar_default = defineTool4({
  name: "log_blood_sugar",
  title: "Log a blood sugar reading",
  description: "Insert a manual blood sugar reading for the signed-in member. Value must be in mg/dL.",
  inputSchema: {
    value_mgdl: z3.number().min(20).max(800).describe("Blood glucose in mg/dL."),
    reading_type: z3.enum(["fasting", "post_meal", "random", "bedtime"]).describe("Context for the reading."),
    measured_at: z3.string().datetime().optional().describe("ISO timestamp; defaults to now."),
    notes: z3.string().max(500).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ value_mgdl, reading_type, measured_at, notes }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("blood_sugar_readings").insert({
      member_id: ctx.getUserId(),
      value_mgdl,
      reading_type,
      measured_at: measured_at ?? (/* @__PURE__ */ new Date()).toISOString(),
      source: "manual",
      notes: notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${value_mgdl} mg/dL (${reading_type}).` }],
      structuredContent: { reading: data }
    };
  }
});

// src/lib/mcp/tools/log-health.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_health_default = defineTool5({
  name: "log_daily_health",
  title: "Log daily health entry",
  description: "Upsert today's daily health log (weight in lbs, energy 1-10, notes) for the signed-in member.",
  inputSchema: {
    weight_lbs: z4.number().min(50).max(700).optional(),
    energy: z4.number().int().min(1).max(10).optional(),
    notes: z4.string().max(1e3).optional(),
    log_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("YYYY-MM-DD; defaults to today (UTC).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ weight_lbs, energy, notes, log_date }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (weight_lbs == null && energy == null && !notes)
      return {
        content: [{ type: "text", text: "Provide at least one of weight_lbs, energy, or notes." }],
        isError: true
      };
    const client = sb5(ctx);
    const date = log_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await client.from("health_logs").upsert(
      {
        user_id: ctx.getUserId(),
        log_date: date,
        weight: weight_lbs ?? null,
        energy: energy ?? null,
        notes: notes ?? null
      },
      { onConflict: "user_id,log_date" }
    ).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved health log for ${date}.` }],
      structuredContent: { log: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-health.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_health_default = defineTool6({
  name: "list_recent_health_logs",
  title: "List recent health logs",
  description: "Return the signed-in member's recent daily health logs (weight, energy, notes), newest first.",
  inputSchema: {
    days: z5.number().int().min(1).max(180).optional().describe("Days back (default 14).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const since = new Date(Date.now() - (days ?? 14) * 864e5).toISOString().slice(0, 10);
    const { data, error } = await sb6(ctx).from("health_logs").select("log_date, weight, blood_sugar, energy, notes").eq("user_id", ctx.getUserId()).gte("log_date", since).order("log_date", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { logs: data }
    };
  }
});

// src/lib/mcp/tools/complete-day.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^4.4.3";
function sb7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var complete_day_default = defineTool7({
  name: "complete_program_day",
  title: "Mark a program day complete",
  description: "Mark a specific program day complete for the signed-in member. The database enforces that the day must already be unlocked.",
  inputSchema: {
    day_number: z6.number().int().min(1).max(120),
    notes: z6.string().max(1e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ day_number, notes }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb7(ctx).from("member_progress").insert({
      user_id: ctx.getUserId(),
      day_number,
      notes: notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Day ${day_number} marked complete.` }],
      structuredContent: { progress: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wqennhjdojjqmmqzjhti";
var mcp_default = defineMcp({
  name: "diabetes-reset-method",
  title: "The Diabetes Reset Method",
  version: "0.1.0",
  instructions: "Tools for signed-in members of The Diabetes Reset Method. Read the member's current program day and streaks, view or log blood sugar readings and daily health entries (weight, energy, notes), fetch today's daily action, and mark program days complete. All calls act as the signed-in user under the app's RLS. This is educational \u2014 not medical advice.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_program_status_default,
    get_today_action_default,
    list_blood_sugar_default,
    log_blood_sugar_default,
    log_health_default,
    list_recent_health_default,
    complete_day_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
