
-- Phase 1 scaffold rows for daily_actions (Section 34).
-- Insert only when a row for that day_number doesn't already exist.

INSERT INTO public.daily_actions
  (day_number, phase_number, day_name, action_title, action_description, action_type, sub_tasks, is_extension_day, learning_objective, action_detail_content)
SELECT * FROM (VALUES
  (1, 1, 'Day 1: The Plate Method',
    'The Plate Method',
    'Build every plate today around the 50/25/25 rule: half non-starchy vegetables, a quarter protein, a quarter slow carbs. One simple structure — used at every meal.',
    'habit', '[]'::jsonb, false,
    'Understand and apply the 50/25/25 plate structure.', '{}'::jsonb),
  (2, 1, 'Day 2: Water Target',
    'Water Target',
    'Calculate your personal daily water target (half your body weight in ounces) and hit it for the first time today. A large bottle next to you makes this easy.',
    'habit', '[]'::jsonb, false,
    'Know your water target and hit it once.', '{}'::jsonb),
  (3, 1, 'Day 3: Protein First',
    'Protein First',
    'Eat your protein component before your carbohydrates at every meal today. This single change lowers post-meal glucose spikes — and it works immediately.',
    'habit', '[]'::jsonb, false,
    'Experience the protein-first effect on blood sugar.', '{}'::jsonb),
  (4, 1, 'Day 4: Non-Starchy Vegetables',
    'Non-Starchy Vegetables',
    'Identify what counts as non-starchy and fill half your plate with them at lunch and dinner today. Volume matters here — be generous.',
    'habit', '[]'::jsonb, false,
    'Recognize non-starchy vegetables and use them as the base of every plate.', '{}'::jsonb),
  (5, 1, 'Day 5: Read a Label',
    'Read a Label',
    'Find one packaged food you eat regularly and read its nutrition label end to end. Focus on serving size, total carbs, and added sugars.',
    'education', '[]'::jsonb, false,
    'Build the habit of checking labels before eating.', '{}'::jsonb),
  (6, 1, 'Day 6: The Full Plate',
    'The Full Plate',
    'Three compliant meals today using the complete plate method. Protein first, half the plate vegetables, water with each meal.',
    'challenge', '[]'::jsonb, false,
    'Execute a full compliant day for the first time.', '{}'::jsonb),
  (7, 1, 'Day 7: First Blood Sugar Check',
    'First Blood Sugar Check',
    'Log your fasting blood sugar this morning. This is your real starting line — no judgment, just data we can track.',
    'measurement', '[]'::jsonb, false,
    'Capture a baseline blood sugar reading.', '{}'::jsonb),
  (8, 1, 'Day 8: Post-Meal Walk',
    'Post-Meal Walk',
    'Ten minutes of walking after each meal today. It moves glucose into your muscles instead of your bloodstream — and it sets up Phase 2.',
    'habit', '[]'::jsonb, false,
    'Feel how movement after meals changes how you feel.', '{}'::jsonb),
  (9, 1, 'Day 9: Portion Audit',
    'Portion Audit',
    'At one meal today, measure your carbohydrate portion against the quarter-plate rule. Most people are surprised by what they find.',
    'reflection', '[]'::jsonb, false,
    'Calibrate your eye for proper carbohydrate portions.', '{}'::jsonb),
  (10, 1, 'Day 10: The Swap',
    'The Swap',
    'Replace one non-compliant food you would normally eat with a compliant alternative. One swap, one win.',
    'challenge', '[]'::jsonb, false,
    'Practice making a real-world compliant substitution.', '{}'::jsonb),
  (11, 1, 'Day 11: Hydration Consistency',
    'Hydration Consistency',
    'Hit your full water goal before 6 PM today. Front-loading hydration prevents the evening cravings most people fight.',
    'habit', '[]'::jsonb, false,
    'Use timing to make hydration effortless.', '{}'::jsonb),
  (12, 1, 'Day 12: Snack Timing',
    'Snack Timing',
    'Eat snack 1 exactly two and a half hours after breakfast today. Right timing keeps blood sugar from dipping into cravings territory.',
    'habit', '[]'::jsonb, false,
    'Understand why snack timing matters as much as snack content.', '{}'::jsonb),
  (13, 1, 'Day 13: Full Compliance Day',
    'Full Compliance Day',
    'Three fully compliant meals, water goal met, both snacks timed correctly. A complete day — proof that the structure works for you.',
    'challenge', '[]'::jsonb, false,
    'Execute a full compliant day end-to-end.', '{}'::jsonb),
  (14, 1, 'Day 14: Phase 1 Complete',
    'Phase 1 Complete',
    'Reflect on the last 14 days and log your weight and fasting blood sugar. Compare them to Day 1. This is your first measurable proof.',
    'measurement', '[]'::jsonb, false,
    'Close Phase 1 with measurable evidence of change.', '{}'::jsonb)
) AS v(day_number, phase_number, day_name, action_title, action_description, action_type, sub_tasks, is_extension_day, learning_objective, action_detail_content)
WHERE NOT EXISTS (
  SELECT 1 FROM public.daily_actions d
  WHERE d.day_number = v.day_number AND d.is_extension_day = v.is_extension_day
);
